---
- name: "OpenWrt DNS sync"
  hosts: openwrt
  roles:
    - name: gekmihesg.openwrt
  # ansible-galaxy role install --role-file requirements-mlavi.yaml
  vars:
    ansible_user: root
    dns_upsert: # no defaults, so empty item type will not work
      - { host: "test1.{{ domain }}", type: CNAME, data: "nas-atx.{{ domain }}" }
      - { host: "test1.{{ domain }}", type: CNAME, data: "nas-itx.{{ domain }}" }
      - { host: "test8.{{ domain }}", type: A, data: "192.168.1.78" }
      - { host: "test8.{{ domain }}", type: A, data: "192.168.1.88" }
    domain: home.lavi.us
  # https://github.com/pe-pe/ansible_role_openwrt_config_dhcp/blob/main/tasks/main.yml
  # https://openwrt.org/docs/guide-user/base-system/uci#append_an_entry_to_a_list
  gather_facts: false
  tasks:
    - name: "Add DNS A record(s)"
      when: item.type == 'A'
      uci:
        command: section
        key: dhcp
        type: domain
        find_by:
          name: "{{ item.host }}"
        value:
          ip: "{{ item.data }}"
          name: "{{ item.host }}"
      with_items: "{{ dns_upsert }}"
    - name: "Add DNS CNAME record(s)"
      when: item.type == 'CNAME'
      uci:
        command: section
        key: dhcp
        type: cname
        find_by:
          name: "{{ item.host }}"
        value:
          cname: "{{ item.host }}"
          target: "{{ item.data }}"
      with_items: "{{ dns_upsert }}"
    - name: "Get DHCP list"
      uci:
        command: show
        key: dhcp
      register: dhcp_list
    - name: "Filter CNAME(s)"
      when: "'cname' in item"
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_items: "{{ dhcp_list.result.split() }}"
    - name: "Filter A(s)"
      when: "'domain' in item"
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_items: "{{ dhcp_list.result.split() }}"
    - name: "Commit UCI changes"
      uci:
        command: commit
    - name: "Reload service dnsmasq, in all cases"
      service:
        name: dnsmasq
        state: restarted
    - name: "Manual Delete Note"
      ansible.builtin.debug:
        msg: "ssh openwrt uci show dhcp | grep cname; uci delete dhcp.@cname[-1] \
          && uci commit dhcp && service dnsmasq restart # last on list"
      #gekmihesg.openwrt. community.general.openwrt_init:
    #   notify: reload wifi
    #   register: command_result
    #   changed_when: "'WERR_DNS_ERROR_RECORD_ALREADY_EXISTS' not in command_result.stderr"
    #   failed_when: command_result.rc > 1 and command_result.rc < 255
    #   register: command_result
    #   with_items: "{{ dns_upsert }}"
    # - name: "Display query result:"
    #   ansible.builtin.debug:
    #     msg: "{{ item.rc }}"
    #   with_items: "{{ command_result.results }}"
    # - name: "Revert pending changes"
    #   uci:
    #     command: revert
