---
- name: "Ansible-NAS: mlavi.homelab enhancements and overrides"
  hosts: vagrant
  pre_tasks:
    # - name: "Show facts available on the system"
    #   ansible.builtin.debug:
    #     var: "ansible_facts"
    - name: "Import family"
      ansible.builtin.import_role:
        name: mlavi.developer.family
  roles:
    - role: ansible-nas-users
      tags:
        - ansible-nas-users
        - ansible-nas
    - role: vladgh.samba.server
      tags:
        - samba
        - skip_ansible_lint
    # - role: geerlingguy.nfs
    #   tags:
    #     - nfs
    #     - skip_ansible_lint
    - role: ansible-nas-general
      tags:
        - ansible-nas-general
        - ansible-nas
  tasks:
    - name: "User+group hard coded to 'ansible-nas':"
      ansible.builtin.debug:
        msg:
          - "roles/ansible-nas-{general,users}/tasks/main.yml"
          - "TODO: append group ansible-nas to ansible_user determintation, because not ansible unless bootstrapped"
    - name: "Append linux_users with group: ansible-nas"
      ansible.builtin.user:
        append: true
        groups:
          - ansible-nas
        name: "{{ item.name }}"
      with_items:
        - "{{ linux_users }}"
