---
- name: "Bootstrap Server"
  hosts: "nas"
  # p task
  # p task.args
  # p task_vars
  tasks:
    - name: "Configure systemd-networkd-wait-online.service"
      when: ansible_facts['distribution'] == "Ubuntu"
      # https://unix.stackexchange.com/questions/381448/systemd-networkd-wait-online-failure
      # https://www.freedesktop.org/software/systemd/man/latest/systemd-networkd-wait-online.service.html
      # sudo EDITOR=vi systemctl edit systemd-networkd-wait-online.service
      block:
        - name: "Prepare systemd-networkd-wait-online.service.d"
          ansible.builtin.file:
            group: "root"
            mode: "a+rx,u+w"
            owner: "root"
            path: "{{ systemd_networkd_wait_online }}"
            state: "directory"
        - name: "Configure systemd-networkd-wait-online.service.d"
          ansible.builtin.copy:
            content: "[Service]\nExecStart=\nExecStart=/usr/lib/systemd/systemd-networkd-wait-online --any --timeout=45\n"
            dest: "{{ systemd_networkd_wait_online }}/override.conf"
            force: false
            group: "root"
            mode: "a+r,u+w"
            owner: "root"
      always:
        - name: "Import https://asdf-vm.com role"
          tags: "asdf"
          ansible.builtin.import_role:
            name: "cimon-io.asdf"
            # debugger> p task_vars['asdf_user']
        - name: "Configure .bash_aliases"
          ansible.builtin.copy:
            content: "source ${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/bashrc && echo '|SOURCE|ASDF|https://direnv.net'\nalias da='direnv allow'\n"
            dest: "/home/{{ ansible_user }}/.bash_aliases"
            force: false
            group: "{{ ansible_user }}"
            mode: "a+r,u+w"
            owner: "{{ ansible_user }}"
        - name: "Tech Debt"
          ansible.builtin.debug:
            # var: "ansible_user"
            # var: "ansible_facts"
            msg:
              - "TODO: Improve Hook asdf::direnv to shell: hardcoded to ansible_user"
        # - name: "Hook asdf::direnv to shell"
        #   tags: "asdf"
        #   ansible.builtin.shell:
        #     cmd: "/etc/profile.d/asdf.sh && asdf direnv setup --version latest"
        #       --shell bash
        #       source "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/bashrc"
        - name: "Stat last apt run"
          # https://jon.sprig.gs/blog/post/1525
          ansible.builtin.stat:
            path: "/var/cache/apt/pkgcache.bin"
          register: "apt_run"
        - name: "Check apt {update,full-upgrade,autoremove,autoclean}"
          when: "'%Y-%m-%d' | strftime(apt_run.stat.mtime) in ansible_date_time.date"
          ansible.builtin.debug:
            msg: "Skipping apt-update, etc. actions as apt update was run today"
        - name: "Perform apt {update,full-upgrade,autoremove,autoclean}"
          when: "'%Y-%m-%d' | strftime(apt_run.stat.mtime) not in ansible_date_time.date"
          ansible.builtin.apt:
            upgrade: "full"
            update_cache: yes
            autoremove: yes
            autoclean: yes
        - name: "Import admin"
          ansible.builtin.import_role:
            name: mlavi.developer.admin
        - name: "Import family"
          ansible.builtin.import_role:
            name: mlavi.developer.family
