---
- name: "Ansible-NAS: mlavi.homelab enhancements and overrides"
  hosts: "vagrant"
  collections:
    - "vladgh.samba.server"
    - "mlavi.developer"
  pre_tasks:
    # - name: "Show facts available on the system"
    #   ansible.builtin.debug:
    #     var: "ansible_facts"
    - name: "Import family"
      ansible.builtin.import_role:
        name: "family"
      tags:
        - ansible-nas-users
  roles:
    - role: ansible-nas-users
      tags:
        - ansible-nas-users
        - ansible-nas
    - role: vladgh.samba.server
      tags:
        - samba
        - skip_ansible_lint
    # - role: geerlingguy.nfs
    #   tags:
    #     - nfs
    #     - skip_ansible_lint
    - role: ansible-nas-general
      tags:
        - ansible-nas-general
        - ansible-nas
  tasks:
    - name: "user+group hard coded to 'ansible-nas':"
      ansible.builtin.debug:
        msg: "roles/ansible-nas-{general,users}/tasks/main.yml"
    - name: "Ammend family + ansible_user"
      ansible.builtin.user:
        name: "{{ item }}"
        groups:
          - "ansible-nas"
        append: true
      loop:
        - "{{ ansible_user }}"
        - "davi"
        - "mari"
        - "mark"
        - "victoria"
