---
- name: "Ansible-NAS"
  hosts: "nas"
  collections:
    - "vladgh.samba.server"
    - "mlavi.homelab"
  tasks:
    # - name: "Show facts available on the system"
    #   ansible.builtin.debug:
    #     var: ansible_facts
    - name: "Note for Raspberry Pi 32-bit OS"
      when: ansible_facts['architecture'] == 'armv7l'
      ansible.builtin.debug:
        msg:
          - "Recommend installing a 64-bit OS (arm64) when possible instead of 32-bit: armfh, etc.
            https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/
            e.g.: ubuntu-22.04.3-preinstalled-server-arm64+raspi.img.xz

            You will see:
            [WARNING]: Docker warning: The requested image's platform (linux/amd64) does not match the detected host platform
            (linux/arm64/v8) and no specific platform was requested

            You will be able to run more 64-bit than 32-bit containers, unless you compile your own."
    # Import new collection roles here; the roles: section below will be overridden.
    # - name: "Import homepage"
    # - name: "Import portainer"
    # Using include_role: {{ item }} is faster and dynamic,
    #   but --start-at-tag can't target? unless role::block::tag used?
    # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html#selectively-running-tagged-tasks-in-reusable-files
    - name: "Import authelia"
      ansible.builtin.import_role:
        name: authelia
    - name: "Import docker-mailserver"
      when: ansible_facts['architecture'] != 'armv7l'
      ansible.builtin.import_role:
        name: docker-mailserver
    - name: "Import gravity"
      ansible.builtin.import_role:
        name: gravity
    - name: "Import keepass4web_rs"
      when: ansible_facts['architecture'] != 'armv7l' or
            ansible_facts['architecture'] != 'linux/arm64/v8' or
            ansible_facts['architecture'] != 'aarch64'
      ansible.builtin.import_role:
        name: keepass4web_rs
    - name: "Import keycloak"
      when: ansible_facts['architecture'] != 'armv7l'
      ansible.builtin.import_role:
        name: keycloak
    - name: "Import webtainer"
      ansible.builtin.import_role:
        name: webtainer

  roles:
    ###
    ### Requirements
    ###
    - role: ansible-nas-users
      tags:
        - ansible-nas-users
        - ansible-nas

    - role: vladgh.samba.server
      tags:
        - samba
        - skip_ansible_lint

    - role: geerlingguy.nfs
      tags:
        - nfs
        - skip_ansible_lint

    - role: geerlingguy.docker
      tags:
        - docker
        - skip_ansible_lint

    ###
    ### Ansible-NAS Roles
    ###
    - role: ansible-nas-general
      tags:
        - ansible-nas-general
        - ansible-nas

    - role: ansible-nas-docker
      tags:
        - ansible-nas-docker
        - ansible-nas

    ###
    ### Stacks
    ###

    - role: logging
      tags:
        - logging


    ###
    ### Applications
    ###
    - role: airsonic
      tags:
        - airsonic

    - role: bazarr
      tags:
        - bazarr

    - role: bitwarden
      tags:
        - bitwarden

    - role: booksonic
      tags:
        - booksonic

    - role: calibre
      tags:
        - calibre

    - role: cloudcmd
      tags:
        - cloudcmd

    - role: cloudflare_ddns
      tags:
        - cloudflare_ddns

    - role: code-server
      tags:
        - code-server

    - role: couchpotato
      tags:
        - couchpotato

    - role: dashy
      tags:
        - dashy

    - role: ddns_updater
      tags:
        - ddns_updater

    - role: deluge
      tags:
        - deluge

    - role: dokuwiki
      tags:
        - dokuwiki

    - role: drone-ci
      tags:
        - drone_ci

    - role: duplicacy
      tags:
        - duplicacy

    - role: duplicati
      tags:
        - duplicati

    - role: emby
      tags:
        - emby

    - role: esphome
      tags:
        - esphome

    - role: firefly
      tags:
        - firefly

    - role: freshrss
      tags:
        - freshrss

    - role: get_iplayer
      tags:
        - get_iplayer

    - role: gitea
      tags:
        - gitea

    - role: gitlab
      tags:
        - gitlab

    - role: glances
      tags:
        - glances

    - role: gotify
      tags:
        - gotify

    - role: guacamole
      tags:
        - guacamole

    - role: healthchecks.io
      tags:
        - healthchecks.io

    - role: heimdall
      when: ansible_facts['architecture'] != 'armv7l'
      tags:
        - heimdall

    - role: hello_world
      tags:
        - hello_world

    - role: homeassistant
      tags:
        - homeassistant

    - role: homebridge
      tags:
        - homebridge

    - role: jackett
      tags:
        - jackett

    - role: jellyfin
      when: ansible_facts['architecture'] != 'armv7l'
      tags:
        - jellyfin

    - role: joomla
      tags:
        - joomla

    - role: komga
      tags:
        - komga

    - role: krusader
      tags:
        - krusader

    - role: lidarr
      tags:
        - lidarr

    - role: loki
      tags:
        - loki

    - role: mealie
      when: ansible_facts['architecture'] != 'armv7l'
      tags:
        - mealie

    - role: minecraft-server
      tags:
        - minecraft-server

    - role: minidlna
      tags:
        - minidlna

    - role: miniflux
      tags:
        - miniflux

    - role: minio
      tags:
        - minio

    - role: mosquitto
      tags:
        - mosquitto

    - role: mumble
      tags:
        - mumble

    - role: mylar
      tags:
        - mylar

    - role: mymediaforalexa
      tags:
        - mymediaforalexa

    - role: n8n
      tags:
        - n8n

    - role: navidrome
      tags:
        - navidrome

    - role: netbootxyz
      tags:
        - netbootxyz

    - role: netdata
      tags:
        - netdata

    - role: nextcloud
      tags:
        - nextcloud

    - role: nomad
      tags:
        - nomad

    - role: nzbget
      tags:
        - nzbget

    - role: octoprint
      tags:
        - octoprint

    - role: ombi
      tags:
        - ombi

    - role: openhab
      tags:
        - openhab

    - role: organizr
      tags:
        - organizr

    - role: overseerr
      tags:
        - overseerr

    - role: paperless_ng
      tags:
        - paperless_ng

    - role: piwigo
      tags:
        - piwigo

    - role: plex
      tags:
        - plex

    - role: portainer
      tags:
        - portainer

    - role: prowlarr
      tags:
        - prowlarr

    - role: promtail
      tags:
        - promtail

    - role: pyload
      tags:
        - pyload

    - role: pytivo
      tags:
        - pytivo

    - role: radarr
      tags:
        - radarr

    - role: route53_ddns
      tags:
        - route53_ddns

    - role: rssbridge
      tags:
        - rssbridge

    - role: sabnzbd
      tags:
        - sabnzbd

    - role: sickchill
      tags:
        - sickchill

    - role: sonarr
      tags:
        - sonarr

    - role: speedtest-tracker
      tags:
        - speedtest-tracker

    - role: stats
      tags:
        - stats

    - role: syncthing
      tags:
        - syncthing

    - role: tautulli
      tags:
        - tautulli

    - role: thelounge
      tags:
        - thelounge

    - role: threadfin
      tags:
        - threadfin

    - role: tiddlywiki
      tags:
        - tiddlywiki

    - role: timemachine
      tags:
        - timemachine

    - role: traefik
      tags:
        - traefik

    - role: transmission
      tags:
        - transmission

    - role: transmission-with-openvpn
      tags:
        - transmission_with_openvpn

    - role: ubooquity
      tags:
        - ubooquity

    - role: utorrent
      tags:
        - utorrent

    - role: virtual_desktop
      tags:
        - virtual_desktop

    - role: wallabag
      tags:
        - wallabag

    - role: watchtower
      tags:
        - watchtower

    - role: wireshark
      tags:
        - wireshark

    - role: woodpecker-ci
      tags:
        - woodpecker_ci

    - role: youtubedlmaterial
      tags:
        - youtubedlmaterial

    - role: znc
      tags:
        - znc
