---
roles:
  - name: geerlingguy.docker
    version: 7.0.2
  # new versions of the role are multi-architecture:
  # https://github.com/geerlingguy/ansible-role-docker_arm deprecated Sep 5, 2023
  - name: geerlingguy.nfs
    version: 2.0.0

collections:
  - name: ansible.posix
  - name: community.docker
  - name: community.general
